version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels: ["area: infrastructure"]
    groups:
      python-development:
        dependency-type: development
      python-runtime:
        dependency-type: production
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels: ["area: infrastructure"]
    groups:
      codeql-suite:
        patterns:
          - "github/codeql-action/*"
        update-types: ["major", "minor", "patch"]
      actions-minor-patch:
        exclude-patterns:
          - "github/codeql-action/*"
        update-types: ["minor", "patch"]
