"""Canonical, MCP-independent Board IR v0.1 contracts."""

from copper_mcp.board_ir.canonical import (
    canonical_content_bytes,
    constraint_digest,
    encode_snapshot,
    make_content,
    make_snapshot,
    verify_snapshot,
)
from copper_mcp.board_ir.codec import decode_snapshot_json
from copper_mcp.board_ir.diagnostics import ConversionResult, Diagnostic, Severity
from copper_mcp.board_ir.limits import ParseLimits
from copper_mcp.board_ir.types import (
    Arc,
    BoardIRContent,
    BoardIRSnapshot,
    ConstraintSet,
    DifferentialPairRule,
    Keepout,
    Layer,
    LengthRule,
    Net,
    NetClass,
    NetClassAssignment,
    OutlineContour,
    Pad,
    PadKind,
    PadShape,
    PointNM,
    Ring,
    Segment,
    SourceInfo,
    UnitSystem,
    Via,
    ViaKind,
    Zone,
    mm_to_nm,
    nm_to_mm,
    normalize_rotation_udeg,
)
from copper_mcp.board_ir.validation import BoardIRValidationError, validate_content

__all__ = [
    "Arc",
    "BoardIRContent",
    "BoardIRSnapshot",
    "BoardIRValidationError",
    "ConstraintSet",
    "ConversionResult",
    "Diagnostic",
    "DifferentialPairRule",
    "Keepout",
    "Layer",
    "LengthRule",
    "Net",
    "NetClass",
    "NetClassAssignment",
    "OutlineContour",
    "Pad",
    "PadKind",
    "PadShape",
    "ParseLimits",
    "PointNM",
    "Ring",
    "Segment",
    "Severity",
    "SourceInfo",
    "UnitSystem",
    "Via",
    "ViaKind",
    "Zone",
    "canonical_content_bytes",
    "constraint_digest",
    "decode_snapshot_json",
    "encode_snapshot",
    "make_content",
    "make_snapshot",
    "mm_to_nm",
    "nm_to_mm",
    "normalize_rotation_udeg",
    "validate_content",
    "verify_snapshot",
]
