"""Deterministic candidate-first routing contracts and reference backends."""

from copper_mcp.routing.astar import (
    ROUTER_VERSION,
    ROUTING_POLICY,
    AStarRouter,
    VerifiedFill,
    canonical_candidate_bytes,
    verify_candidate_id,
)
from copper_mcp.routing.contracts import (
    COMPONENT_MST_ORDERING,
    SINGLE_PATH_ORDERING,
    AStarSettings,
    CancellationCheck,
    RouteCandidate,
    RouteConnection,
    RouteCost,
    RouteDiagnostic,
    RouteFailureCode,
    RouteMetrics,
    RoutePatch,
    RoutePath,
    RouteRequest,
    RouteResult,
    RoutingBackend,
)

__all__ = [
    "COMPONENT_MST_ORDERING",
    "ROUTER_VERSION",
    "ROUTING_POLICY",
    "SINGLE_PATH_ORDERING",
    "AStarRouter",
    "AStarSettings",
    "CancellationCheck",
    "RouteCandidate",
    "RouteConnection",
    "RouteCost",
    "RouteDiagnostic",
    "RouteFailureCode",
    "RouteMetrics",
    "RoutePatch",
    "RoutePath",
    "RouteRequest",
    "RouteResult",
    "RoutingBackend",
    "VerifiedFill",
    "canonical_candidate_bytes",
    "verify_candidate_id",
]
